### PR TITLE
Ci mtcp

### PR DESCRIPTION
**Pull request by kevindweb**
Testing again

### CODE REVIEW

**Comment by onvm** [comment]
> In response to PR creation

## CI Message

Your results will arrive shortly

**Comment by kevindweb** [comment]
@onvm working?

**Comment by onvm** [comment]
> @onvm working?

## CI Message

Your results will arrive shortly

**Comment by onvmstats** [comment]
gotcha here

**Comment by onvmstats** [comment]
@onvm here?

**Comment by onvmstats** [comment]
@onvm now here

**Comment by onvm** [comment]
> @onvm now here

## CI Message

Aborting, need an authorized user to run CI

**Comment by kevindweb** [comment]
@onvm test me

**Comment by onvm** [comment]
> @onvm test me

## CI Message

Your results will arrive shortly

**Comment by kevindweb** [comment]
@onvm test?

**Comment by kevindweb** [comment]
@onvm here?

**Comment by onvm** [comment]
> @onvm here?

## CI Message

Your results will arrive shortly

**Comment by kevindweb** [comment]
@onvm test

**Comment by onvm** [comment]
> @onvm test

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm test

## CI Message

Error: Failed to parse nimbnode23 stats

**Comment by kevindweb** [comment]
@onvm start?

**Comment by onvm** [comment]
> @onvm start?

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm start?

## CI Message

Error: Failed to post results to GitHub

**Comment by kevindweb** [comment]
@onvm im glad we have a test instance

**Comment by onvm** [comment]
> @onvm im glad we have a test instance

## CI Message

Your results will arrive shortly

**Review by onvm — APPROVED** [review]
> @onvm im glad we have a test instance

## CI Message

Run successful see results:
Test took: 1 second
 :heavy_check_mark: Pktgen performance check passed
 :heavy_check_mark: Speed Tester performance check passed
 :x: PR drops {} NF chain failed with errors, see below
[Results from nimbnode23]

 - Median TX pps for Pktgen: 7737192                          
  Performance rating - 100.00% (compared to 7700000 average)

 - Median TX pps for Speed Tester: 42231513                          
  Performance rating - 100.55% (compared to 42000000 average)### NF Chain Results<details><summary>Speed Tester 1</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 2
NF service ID: 1
NF assigned core: 4
----------------------------------------------------
RX total: 30536928
RX total dropped: 0
TX total: 30552896
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30548143
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details><details><summary>Speed Tester 4</summary>     <br><pre>
line 789 main.c

 segmentation fault 
</pre></details><details><summary>Simple Forward 2</summary>     <br><pre>NF tag: simple_forward
NF instance ID: 1
NF service ID: 2
NF assigned core: 3
----------------------------------------------------
RX total: 30552896
RX total dropped: 0
TX total: 30536928
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30536928
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 0
</pre></details><details><summary>Speed Tester 3</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 3
NF service ID: 3
NF assigned core: 5
----------------------------------------------------
RX total: 66358432
RX total dropped: 0
TX total: 66358432
TX total dropped: 0
NF sent out: 0
NF sent to NF: 66350027
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details><details><summary>Speed Tester 1</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 2
NF service ID: 1
NF assigned core: 4
----------------------------------------------------
RX total: 30536928
RX total dropped: 0
TX total: 30552896
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30548143
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details><details><summary>Simple Forward 2</summary>     <br><pre>NF tag: simple_forward
NF instance ID: 1
NF service ID: 2
NF assigned core: 3
----------------------------------------------------
RX total: 30552896
RX total dropped: 0
TX total: 30536928
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30536928
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 0
</pre></details><details><summary>Speed Tester 3</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 3
NF service ID: 3
NF assigned core: 5
----------------------------------------------------
RX total: 66358432
RX total dropped: 0
TX total: 66358432
TX total dropped: 0
NF sent out: 0
NF sent to NF: 66350027
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>

**Comment by kevindweb** [comment]
@onvm at it again with the white vans

**Comment by onvm** [comment]
> @onvm at it again with the white vans

## CI Message

Your results will arrive shortly

**Review by onvm — APPROVED** [review]
> @onvm at it again with the white vans

## CI Message

Run successful see results:
Test took: 2 seconds
 :heavy_check_mark: Pktgen performance check passed
 :heavy_check_mark: Speed Tester performance check passed
 :x: PR drops {} NF chain failed with errors, see below
[Results from nimbnode23]

 - Median TX pps for Pktgen: 7737192                          
  Performance rating - 100.00% (compared to 7700000 average)

 - Median TX pps for Speed Tester: 42231513                          
  Performance rating - 100.55% (compared to 42000000 average)
### NF Chain Results
<details><summary>Speed Tester 1</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 2
NF service ID: 1
NF assigned core: 4
----------------------------------------------------
RX total: 30536928
RX total dropped: 0
TX total: 30552896
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30548143
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>
<details><summary>Speed Tester 4</summary>     <br><pre>
line 789 main.c

 segmentation fault 
</pre></details>
<details><summary>Simple Forward 2</summary>     <br><pre>NF tag: simple_forward
NF instance ID: 1
NF service ID: 2
NF assigned core: 3
----------------------------------------------------
RX total: 30552896
RX total dropped: 0
TX total: 30536928
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30536928
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 0
</pre></details>
<details><summary>Speed Tester 3</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 3
NF service ID: 3
NF assigned core: 5
----------------------------------------------------
RX total: 66358432
RX total dropped: 0
TX total: 66358432
TX total dropped: 0
NF sent out: 0
NF sent to NF: 66350027
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>
<details><summary>Speed Tester 1</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 2
NF service ID: 1
NF assigned core: 4
----------------------------------------------------
RX total: 30536928
RX total dropped: 0
TX total: 30552896
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30548143
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>
<details><summary>Simple Forward 2</summary>     <br><pre>NF tag: simple_forward
NF instance ID: 1
NF service ID: 2
NF assigned core: 3
----------------------------------------------------
RX total: 30552896
RX total dropped: 0
TX total: 30536928
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30536928
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 0
</pre></details>
<details><summary>Speed Tester 3</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 3
NF service ID: 3
NF assigned core: 5
----------------------------------------------------
RX total: 66358432
RX total dropped: 0
TX total: 66358432
TX total dropped: 0
NF sent out: 0
NF sent to NF: 66350027
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>

**Comment by kevindweb** [comment]
@onvm s

**Comment by onvm** [comment]
> @onvm s

## CI Message

Your results will arrive shortly

**Review by onvm — CHANGES_REQUESTED** [review]
> @onvm s

## CI Message

Run successful see results:
Test took: 1 second
 :heavy_check_mark: Pktgen performance check passed
 :heavy_check_mark: Speed Tester performance check passed
 :x: NF chain failed with errors, see below

[Results from nimbnode23]

 - Median TX pps for Pktgen: 7737192                          
  Performance rating - 100.00% (compared to 7700000 average)

 - Median TX pps for Speed Tester: 42231513                          
  Performance rating - 100.55% (compared to 42000000 average)
### NF Chain Results
<details><summary>Speed Tester 1</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 2
NF service ID: 1
NF assigned core: 4
----------------------------------------------------
RX total: 30536928
RX total dropped: 0
TX total: 30552896
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30548143
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>
<details><summary>Speed Tester 4</summary>     <br><pre>
line 789 main.c

 segmentation fault 
</pre></details>
<details><summary>Simple Forward 2</summary>     <br><pre>NF tag: simple_forward
NF instance ID: 1
NF service ID: 2
NF assigned core: 3
----------------------------------------------------
RX total: 30552896
RX total dropped: 0
TX total: 30536928
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30536928
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 0
</pre></details>
<details><summary>Speed Tester 3</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 3
NF service ID: 3
NF assigned core: 5
----------------------------------------------------
RX total: 66358432
RX total dropped: 0
TX total: 66358432
TX total dropped: 0
NF sent out: 0
NF sent to NF: 66350027
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>
<details><summary>Speed Tester 1</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 2
NF service ID: 1
NF assigned core: 4
----------------------------------------------------
RX total: 30536928
RX total dropped: 0
TX total: 30552896
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30548143
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>
<details><summary>Simple Forward 2</summary>     <br><pre>NF tag: simple_forward
NF instance ID: 1
NF service ID: 2
NF assigned core: 3
----------------------------------------------------
RX total: 30552896
RX total dropped: 0
TX total: 30536928
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30536928
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 0
</pre></details>
<details><summary>Speed Tester 3</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 3
NF service ID: 3
NF assigned core: 5
----------------------------------------------------
RX total: 66358432
RX total dropped: 0
TX total: 66358432
TX total dropped: 0
NF sent out: 0
NF sent to NF: 66350027
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>

**Comment by kevindweb** [comment]
@onvm should

**Comment by onvm** [comment]
> @onvm should
> 

## CI Message

Your results will arrive shortly

**Review by onvm — CHANGES_REQUESTED** [review]
> @onvm should
> 

## CI Message

Run successful see results:
Test took: 1 second
 :heavy_check_mark: Pktgen performance check passed
 :heavy_check_mark: Speed Tester performance check passed
 :x: NF chain failed with errors, see below

[Results from nimbnode23]

 - Median TX pps for Pktgen: 7737192                          
  Performance rating - 100.00% (compared to 7700000 average)

 - Median TX pps for Speed Tester: 42231513                          
  Performance rating - 100.55% (compared to 42000000 average)
### NF Chain Results
<details><summary>Speed Tester 1</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 2
NF service ID: 1
NF assigned core: 4
----------------------------------------------------
RX total: 30536928
RX total dropped: 0
TX total: 30552896
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30548143
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>
<details><summary>Speed Tester 4 (errors)</summary>     <br><pre>
line 789 main.c

 segmentation fault 
</pre></details>
<details><summary>Simple Forward 2</summary>     <br><pre>NF tag: simple_forward
NF instance ID: 1
NF service ID: 2
NF assigned core: 3
----------------------------------------------------
RX total: 30552896
RX total dropped: 0
TX total: 30536928
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30536928
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 0
</pre></details>
<details><summary>Speed Tester 3</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 3
NF service ID: 3
NF assigned core: 5
----------------------------------------------------
RX total: 66358432
RX total dropped: 0
TX total: 66358432
TX total dropped: 0
NF sent out: 0
NF sent to NF: 66350027
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>
<details><summary>Speed Tester 1</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 2
NF service ID: 1
NF assigned core: 4
----------------------------------------------------
RX total: 30536928
RX total dropped: 0
TX total: 30552896
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30548143
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>
<details><summary>Simple Forward 2</summary>     <br><pre>NF tag: simple_forward
NF instance ID: 1
NF service ID: 2
NF assigned core: 3
----------------------------------------------------
RX total: 30552896
RX total dropped: 0
TX total: 30536928
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30536928
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 0
</pre></details>
<details><summary>Speed Tester 3</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 3
NF service ID: 3
NF assigned core: 5
----------------------------------------------------
RX total: 66358432
RX total dropped: 0
TX total: 66358432
TX total dropped: 0
NF sent out: 0
NF sent to NF: 66350027
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>

**Comment by kevindweb** [comment]
@onvm

**Comment by onvm** [comment]
> @onvm 

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm 

## CI Message

Error: Failed to parse nimbnode23 stats

**Comment by kevindweb** [comment]
@onvm kickoff

**Comment by onvm** [comment]
> @onvm kickoff

## CI Message

Your results will arrive shortly

**Review by onvm — APPROVED** [review]
> @onvm kickoff

## CI Message

Run successful see results:
Test took: 1 second
 :heavy_check_mark: Pktgen performance check passed
 :heavy_check_mark: Speed Tester performance check passed
 :heavy_check_mark: NF chain succeeded

[Results from nimbnode23]

 - Median TX pps for Pktgen: 7737192                          
  Performance rating - 100.00% (compared to 7700000 average)

 - Median TX pps for Speed Tester: 42231513                          
  Performance rating - 100.55% (compared to 42000000 average)
### NF Chain Results
<details><summary>Speed Tester 1</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 2
NF service ID: 1
NF assigned core: 4
----------------------------------------------------
RX total: 30536928
RX total dropped: 0
TX total: 30552896
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30548143
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>
<details><summary>Simple Forward 2</summary>     <br><pre>NF tag: simple_forward
NF instance ID: 1
NF service ID: 2
NF assigned core: 3
----------------------------------------------------
RX total: 30552896
RX total dropped: 0
TX total: 30536928
TX total dropped: 0
NF sent out: 0
NF sent to NF: 30536928
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 0
</pre></details>
<details><summary>Speed Tester 3</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 3
NF service ID: 3
NF assigned core: 5
----------------------------------------------------
RX total: 66358432
RX total dropped: 0
TX total: 66358432
TX total dropped: 0
NF sent out: 0
NF sent to NF: 66350027
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>

**Comment by kevindweb** [comment]
@onvm wanna try

**Comment by kevindweb** [comment]
@onvm

**Comment by onvm** [comment]
> @onvm

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm

## CI Message

Error: Failed to copy ONVM files to nimbnode23

**Comment by kevindweb** [comment]
@onvm test

**Comment by onvm** [comment]
> @onvm test

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm test

## CI Message

Error: Failed to fetch results from nimbnode23

**Comment by kevindweb** [comment]
@onvm failure imminent

**Comment by onvm** [comment]
> @onvm failure imminent

## CI Message

Your results will arrive shortly

**Review by onvm — APPROVED** [review]
> @onvm failure imminent

## CI Message

Run successful see results:
Test took: 7 minutes, 31 seconds
 :heavy_check_mark: Pktgen performance check passed
 :heavy_check_mark: Speed Tester performance check passed
 :heavy_check_mark: NF chain succeeded

[Results from nimbnode23]

 - Median TX pps for Pktgen: 7753849                          
  Performance rating - 100.00% (compared to 7700000 average)

 - Median TX pps for Speed Tester: 42109313                          
  Performance rating - 100.26% (compared to 42000000 average)
### NF Chain Results
<details><summary>Speed Tester 1</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 5
NF service ID: 1
NF assigned core: 6
----------------------------------------------------
RX total: 62419488
RX total dropped: 0
TX total: 62434048
TX total dropped: 0
NF sent out: 0
NF sent to NF: 62427427
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 14654
</pre></details>
<details><summary>Simple Forward 2</summary>     <br><pre>NF tag: simple_forward
NF instance ID: 4
NF service ID: 2
NF assigned core: 5
----------------------------------------------------
RX total: 62434078
RX total dropped: 0
TX total: 62419488
TX total dropped: 0
NF sent out: 0
NF sent to NF: 62419488
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 0
</pre></details>
<details><summary>Speed Tester 3</summary>     <br><pre>NF tag: speed_tester
NF instance ID: 3
NF service ID: 3
NF assigned core: 4
----------------------------------------------------
RX total: 232643808
RX total dropped: 0
TX total: 232643712
TX total dropped: 0
NF sent out: 0
NF sent to NF: 232636668
NF dropped: 0
NF next: 0
NF tx buffered: 0
NF tx returned: 16000
</pre></details>

**Comment by kevindweb** [comment]
aesflkjasef

**Comment by catherinemeadows** [comment]
@onvm test

**Comment by onvm** [comment]
> @onvm test 

## CI Message

Your results will arrive shortly

**Comment by onvm** [comment]
> @onvm test 

## CI Message

Error: Failed to parse Pktgen stats

**Comment by onvmstats** [comment]
@test

**Comment by kevindweb** [comment]
@deploy

**Comment by kevindweb** [comment]
@deploy

**Comment by kevindweb** [comment]
@deploymehere

**Pull request closed without merging**
